name: Integration Tests

on:
  pull_request:
    branches: [main-FIXME]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node Environment
        uses: ./.github/setup-node

      - name: Setup FastEdge Run CLI
        uses: ./.github/setup-fastedge-cli
        with:
          github_token: ${{ github.token }}

      - name: Build (including WASM test apps)
        run: pnpm run build:ci-test

      - name: Run tests
        run: pnpm test
